name: Send email
description: Send an email to multiple recipients using SendGrid API
author: apotox
branding:
  icon: mail
  color: blue
inputs:
  sgApiKey:
    description: SendGrid api key
  subject:
    description: Subject of mail message
    required: true
  to:
    description: Recipients mail addresses (separated with comma)
    required: true
  from:
    description: Full name of mail sender (might be with an email address specified in <>)
    required: true
  text:
    description: Body of mail message
    required: true

runs:
  using: node16
  main: main.js
