name: Test action

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - subject: Plain body
            text: |
              first line
              second line
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          sgApiKey: ${{secrets.SG_API_KEY}}
          subject: ${{matrix.subject}}
          text: ${{matrix.text}}
          to: '${{github.event.pusher.email}}'
          from: ${{secrets.FROM_ADDRESS}}

