name: Test action

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - subject: test plain body
            text: |
              first line
              second line
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: hide sender
        id: sender
        run: | 
          PUSHER="${{github.event.pusher.email}}"
          echo "::add-mask::$PUSHER"
          echo "::set-output name=pusher::$PUSHER"
          
      - name: Send mail
        uses: ./
        with:
          sgApiKey: ${{secrets.SG_API_KEY}}
          subject: ${{matrix.subject}}
          text: ${{matrix.text}}
          to: '${{steps.sender.outputs.pusher}}'
          from: ${{secrets.FROM_ADDRESS}}